-- Ledger internal PostgreSQL schema, 2026-09-28.
-- Run only in the empty database "ledgerServer". This file creates no data.
-- SQLite remains the operational database. Only seven tables currently have
-- push/pull support in sync-worker.ts: clients, users, invoice_item_templates,
-- invoices, invoice_items, receipts, customer_ledger.

BEGIN;

CREATE TABLE clients (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  email text,
  phone text,
  address text,
  tax_id text,
  notes text,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE invoice_item_templates (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  description text NOT NULL,
  default_unit_price numeric(12,2) DEFAULT 0,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  item_code text UNIQUE
);

CREATE TABLE users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username text NOT NULL UNIQUE,
  password_hash text NOT NULL,
  display_name text NOT NULL,
  display_name_ar text,
  display_name_en text,
  role text DEFAULT 'user',
  is_active boolean DEFAULT true,
  pending_approval boolean DEFAULT false,
  permissions jsonb,
  email text,
  phone text,
  whatsapp_api_key text,
  two_factor_email boolean DEFAULT false,
  two_factor_whatsapp boolean DEFAULT false,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  receiver_signature_base64 text,
  client_id integer REFERENCES clients(id),
  client_view_permissions jsonb
);

CREATE TABLE invoices (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_number text NOT NULL UNIQUE,
  client_id integer NOT NULL REFERENCES clients(id),
  issue_date text NOT NULL,
  due_date text,
  status text DEFAULT 'draft',
  subtotal numeric(12,2) DEFAULT 0,
  tax_rate numeric(7,2) DEFAULT 0,
  tax_amount numeric(12,2) DEFAULT 0,
  total numeric(12,2) DEFAULT 0,
  notes text,
  shipment_ref text,
  bill_of_lading text,
  package_count integer,
  shipment_weight numeric(14,3),
  port_of_entry text,
  importer_exporter_name text,
  advance_payment numeric(12,2) DEFAULT 0,
  created_by integer REFERENCES users(id),
  deleted_at timestamp,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE invoice_items (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_id integer NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,
  description text NOT NULL,
  quantity numeric(14,3) NOT NULL,
  unit_price numeric(14,2) NOT NULL,
  total numeric(14,2) NOT NULL
);

CREATE TABLE receipts (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  receipt_number text NOT NULL,
  client_id integer NOT NULL REFERENCES clients(id),
  invoice_id integer REFERENCES invoices(id) ON DELETE SET NULL,
  amount numeric(14,2) NOT NULL,
  payment_method text DEFAULT 'cash',
  notes text,
  receipt_date text NOT NULL,
  deleted_at timestamp,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  created_by integer REFERENCES users(id),
  status text NOT NULL DEFAULT 'issued'
);

CREATE TABLE customer_ledger (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id integer NOT NULL REFERENCES clients(id),
  invoice_id integer REFERENCES invoices(id),
  receipt_id integer REFERENCES receipts(id),
  entry_date text NOT NULL,
  entry_type text NOT NULL,
  description_ar text NOT NULL,
  description_en text NOT NULL,
  reference_type text NOT NULL,
  reference_number text,
  debit numeric(14,2) DEFAULT 0,
  credit numeric(14,2) DEFAULT 0,
  balance_impact numeric(14,2) DEFAULT 0,
  created_by integer REFERENCES users(id),
  created_at timestamp DEFAULT CURRENT_TIMESTAMP
);

-- The following tables mirror the current local structure but are not
-- transferred by the existing sync worker.

CREATE TABLE invoice_accounting (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_id integer NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,
  payments numeric(14,2) DEFAULT 0,
  transportation numeric(14,2) DEFAULT 0,
  labor numeric(14,2) DEFAULT 0,
  other_expenses numeric(14,2) DEFAULT 0,
  driver_name text,
  unload_location text,
  transportation_paid boolean DEFAULT false,
  labor_paid boolean DEFAULT false,
  other_expenses_paid boolean DEFAULT false,
  updated_at bigint
);

CREATE TABLE invoice_attachments (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_id integer REFERENCES invoices(id),
  declaration_number text NOT NULL,
  declaration_base_number text NOT NULL,
  file_name text NOT NULL,
  stored_name text NOT NULL,
  relative_path text NOT NULL,
  mime_type text,
  file_size bigint,
  category text NOT NULL DEFAULT 'other',
  storage_provider text NOT NULL DEFAULT 'local',
  created_by integer REFERENCES users(id),
  created_at bigint NOT NULL,
  deleted_at bigint
);

CREATE TABLE invoice_audit_logs (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_id integer NOT NULL REFERENCES invoices(id),
  action text NOT NULL,
  user_id integer REFERENCES users(id),
  username text,
  user_email text,
  user_phone text,
  changes_json text,
  created_at bigint
);

CREATE TABLE otp_codes (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES users(id),
  code text NOT NULL,
  expires_at bigint NOT NULL,
  used_at bigint,
  created_at bigint
);

CREATE TABLE sync_queue (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_type text NOT NULL,
  entity_id text NOT NULL,
  operation text NOT NULL,
  payload_json text,
  status text NOT NULL DEFAULT 'pending',
  retry_count integer NOT NULL DEFAULT 0,
  last_error text,
  synced_at bigint,
  created_at bigint,
  updated_at bigint
);

CREATE TABLE company_settings (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name_ar text NOT NULL DEFAULT 'اسم الشركة للتخليص الجمركي',
  name_en text NOT NULL DEFAULT 'Company Name Customs Clearance',
  subtitle_ar text DEFAULT 'للتخليص الجمركي',
  subtitle_en text DEFAULT 'Customs Clearance',
  tagline_ar text DEFAULT 'خدمات التخليص الجمركي والشحن',
  tagline_en text DEFAULT 'Customs Clearance & Shipping Services',
  email text DEFAULT 'your email', phone text DEFAULT 'your phone',
  address text DEFAULT 'your address', po_box text DEFAULT 'your P.O. Box',
  website text, cr_number text, tax_number text,
  logo_base64 text, stamp_base64 text, watermark_base64 text,
  show_watermark integer DEFAULT 1,
  show_stamp_on_invoices integer DEFAULT 1,
  show_stamp_on_receipts integer DEFAULT 1,
  show_stamp_on_statements integer DEFAULT 1,
  footer_text text,
  invoice_cash_title_ar text, invoice_cash_title_en text,
  invoice_credit_title_ar text, invoice_credit_title_en text,
  invoice_title_font_size integer DEFAULT 25,
  updated_at bigint,
  accountant_signature_base64 text, receiver_signature_base64 text,
  show_accountant_signature integer DEFAULT 1,
  show_receiver_signature integer DEFAULT 1,
  logo_size integer DEFAULT 80,
  master_password_hash text,
  invoice_title_visible integer DEFAULT 1,
  invoice_title_align text DEFAULT 'center',
  invoice_title_bold integer DEFAULT 1,
  invoice_subtitle_ar text DEFAULT '', invoice_subtitle_en text DEFAULT '',
  invoice_subtitle_font_size integer DEFAULT 12,
  statement_title_ar text DEFAULT 'كشف حساب',
  statement_title_en text DEFAULT 'Statement',
  statement_title_font_size integer DEFAULT 18,
  statement_title_visible integer DEFAULT 1,
  statement_title_align text DEFAULT 'center',
  statement_title_bold integer DEFAULT 1,
  statement_subtitle_ar text DEFAULT '', statement_subtitle_en text DEFAULT '',
  statement_subtitle_font_size integer DEFAULT 12,
  customer_ledger_title_ar text DEFAULT 'ملخص العميل المالي',
  customer_ledger_title_en text DEFAULT 'Customer Financial Summary',
  customer_ledger_title_font_size integer DEFAULT 18,
  customer_ledger_title_visible integer DEFAULT 1,
  customer_ledger_title_align text DEFAULT 'center',
  customer_ledger_title_bold integer DEFAULT 1,
  customer_ledger_subtitle_ar text DEFAULT '',
  customer_ledger_subtitle_en text DEFAULT '',
  customer_ledger_subtitle_font_size integer DEFAULT 12,
  allow_manager_edit_accountant_signature integer DEFAULT 0,
  allow_manager_edit_legal_info integer DEFAULT 0,
  allow_manager_edit_invoices_backup_import integer DEFAULT 0,
  allow_manager_edit_appearance integer DEFAULT 0,
  allow_manager_edit_print_settings integer DEFAULT 0,
  allow_manager_view_preview integer DEFAULT 0,
  allow_manager_view_update integer DEFAULT 0,
  allow_manager_edit_branding integer DEFAULT 0,
  allow_manager_edit_registration_settings integer DEFAULT 0,
  allow_manager_edit_sensitive_users integer DEFAULT 0,
  lock_company_identity integer DEFAULT 0,
  lock_company_name integer DEFAULT 0,
  lock_logo integer DEFAULT 0,
  lock_stamp integer DEFAULT 0,
  lock_legal_info integer DEFAULT 0,
  lock_footer_branding integer DEFAULT 0,
  login_footer_text text DEFAULT '',
  prevent_rebrand_to_another_company integer DEFAULT 0,
  license_status text DEFAULT 'not_configured',
  licensed_company_name text DEFAULT '',
  license_id text DEFAULT '', hardware_id text DEFAULT '',
  issued_at text DEFAULT '', expires_at text DEFAULT '',
  developer_username text, developer_password_hash text,
  database_provider text DEFAULT 'sqlite',
  database_mode text DEFAULT 'local',
  database_use_connection_string integer DEFAULT 0,
  database_connection_string text DEFAULT '',
  database_host text DEFAULT '', database_port text DEFAULT '5432',
  database_name text DEFAULT '', database_username text DEFAULT '',
  database_password text DEFAULT '',
  sync_mode text DEFAULT 'local-to-online',
  sync_auto_sync integer DEFAULT 0,
  sync_timing text DEFAULT 'startup',
  sync_interval_minutes integer DEFAULT 30,
  sync_last_sync_time text DEFAULT '',
  sync_status text DEFAULT 'idle',
  login_message_text text DEFAULT '',
  login_message_type text DEFAULT 'welcome',
  logo_height integer DEFAULT 80,
  internal_database_host text DEFAULT '',
  internal_database_port text DEFAULT '5432',
  internal_database_name text DEFAULT '',
  internal_database_username text DEFAULT '',
  internal_database_password text DEFAULT '',
  internal_database_connection_string text DEFAULT '',
  internal_sync_mode text DEFAULT 'bidirectional',
  internal_sync_auto_sync integer DEFAULT 0,
  internal_sync_timing text DEFAULT 'startup',
  internal_sync_interval_minutes integer DEFAULT 30
);

CREATE INDEX invoices_client_id_idx ON invoices(client_id);
CREATE INDEX invoice_items_invoice_id_idx ON invoice_items(invoice_id);
CREATE INDEX receipts_client_id_idx ON receipts(client_id);
CREATE INDEX receipts_invoice_id_idx ON receipts(invoice_id);
CREATE INDEX customer_ledger_client_id_idx ON customer_ledger(client_id);
CREATE INDEX sync_queue_status_idx ON sync_queue(status, retry_count);

COMMIT;

-- Read-only verification after execution:
-- SELECT current_database(), COUNT(*) AS tables
-- FROM information_schema.tables
-- WHERE table_schema = 'public' AND table_type = 'BASE TABLE';
