-- Ledger internal PostgreSQL change journal.
-- Apply to ledgerServer after taking a database backup. Safe to run again.
-- It records only changes made after installation; existing rows are not queued.
BEGIN;

CREATE TABLE IF NOT EXISTS public.internal_sync_journal (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  table_name text NOT NULL,
  row_id integer NOT NULL,
  operation text NOT NULL CHECK (operation IN ('insert', 'update', 'delete')),
  changed_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS internal_sync_journal_row_idx
  ON public.internal_sync_journal (table_name, row_id, id);

CREATE OR REPLACE FUNCTION public.record_internal_sync_change()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $function$
BEGIN
  -- Ledger's local-to-internal push is already tracked in SQLite. Do not
  -- mistake its writes for an independent edit made on the internal server.
  IF current_setting('ledger.internal_sync_origin', true) = 'local' THEN
    IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
    RETURN NEW;
  END IF;

  IF TG_OP = 'DELETE' THEN
    INSERT INTO public.internal_sync_journal (table_name, row_id, operation)
    VALUES (TG_TABLE_NAME, OLD.id, 'delete');
    RETURN OLD;
  END IF;

  INSERT INTO public.internal_sync_journal (table_name, row_id, operation)
  VALUES (TG_TABLE_NAME, NEW.id, lower(TG_OP));
  RETURN NEW;
END;
$function$;

DO $block$
DECLARE table_name text;
BEGIN
  FOREACH table_name IN ARRAY ARRAY[
    'clients', 'users', 'invoice_item_templates', 'invoices', 'invoice_items',
    'invoice_accounting', 'receipts', 'customer_ledger', 'invoice_audit_logs'
  ] LOOP
    EXECUTE format('DROP TRIGGER IF EXISTS ledger_internal_sync_change ON public.%I', table_name);
    EXECUTE format(
      'CREATE TRIGGER ledger_internal_sync_change AFTER INSERT OR UPDATE OR DELETE '
      || 'ON public.%I FOR EACH ROW EXECUTE FUNCTION public.record_internal_sync_change()',
      table_name
    );
  END LOOP;
END;
$block$;

-- The app's configured PostgreSQL role must be allowed to read and consume
-- this queue. The current ledgerServer role is "ledger".
DO $block$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'ledger') THEN
    GRANT SELECT, DELETE ON public.internal_sync_journal TO ledger;
  END IF;
END;
$block$;

COMMIT;

-- Read-only check after installation:
-- SELECT COUNT(*) FROM public.internal_sync_journal;
