import {createHash} from 'node:crypto';
import {readFilters} from './list-query.mjs';
import {recordWhere,assertRecord} from './record-access.mjs';
import {decimal,cash} from './draft.mjs';
const fail=(status,message)=>Object.assign(Error(message),{status});
const fields={payments:'payments',transportation:'transportation',labor:'labor',otherExpenses:'other_expenses',driverName:'driver_name',unloadLocation:'unload_location',transportationPaid:'transportation_paid',laborPaid:'labor_paid',otherExpensesPaid:'other_expenses_paid'};
const numeric=['payments','transportation','labor','otherExpenses'],paid=['transportationPaid','laborPaid','otherExpensesPaid'];
export function canViewAccounting(user){let permissions={};try{permissions=typeof user?.permissions==='string'?JSON.parse(user.permissions):user?.permissions||{};}catch{}return user?.role==='admin'||(['supervisor','manager','user'].includes(user?.role)&&permissions.canViewAccounting===true);}
export function accountingIncome(row){return Math.round((Number(row.subtotal||0)-Number(row.payments||0)-(row.transportationPaid?Number(row.transportation||0):0)-(row.laborPaid?Number(row.labor||0):0)-(row.otherExpensesPaid?Number(row.otherExpenses||0):0))*100)/100;}
export function accountingVersion(row){return createHash('sha256').update(JSON.stringify([Number(row.id),row.created_by==null?null:Number(row.created_by),Number(row.subtotal||0),...Object.keys(fields).map(k=>numeric.includes(k)?Number(row[k]||0):paid.includes(k)?!!row[k]:row[k]||'')])).digest('hex');}
export function validateAccounting(input){const id=Number(input?.id);if(!Number.isSafeInteger(id)||id<=0||!/^([a-f0-9]{64})$/.test(input?.version||''))throw fail(400,'Invalid accounting identity');const data={};try{for(const key of numeric)data[key]=cash(decimal(input[key]??0));}catch{throw fail(400,'المصروفات يجب أن تكون أرقامًا موجبة أو صفرًا بمنزلتين عشريتين / Expenses must be non-negative amounts with at most two decimals');}for(const key of paid){if(typeof input[key]!=='boolean')throw fail(400,'Invalid payment status');data[key]=input[key];}for(const key of ['driverName','unloadLocation']){if(typeof input[key]!=='string'||input[key].length>250)throw fail(400,'Invalid accounting text');data[key]=input[key].trim()||null;}return {id,version:input.version,data};}
export async function accountingSchema(db){const rows=(await db.query("SELECT attname AS name,format_type(atttypid,atttypmod) AS type FROM pg_attribute WHERE attrelid=to_regclass('invoice_accounting') AND attnum>0 AND NOT attisdropped")).rows;const columns=Object.fromEntries(rows.map(r=>[r.name,r.type]));const missing=['invoice_id',...Object.values(fields)].filter(k=>!columns[k]);if(missing.length)throw fail(409,'بيانات الحسابات غير جاهزة في Online؛ يلزم فحص جدول الحسابات ومزامنته / Online accounting data is unavailable; check the accounting table and synchronization');return columns;}
function rowSelect(){const amount=(key,column)=>`COALESCE((a.data->>'${column}')::numeric,0) AS "${key}"`;const flag=(key,column)=>`COALESCE(a.data->>'${column}','false') IN ('true','t','1') AS "${key}"`;return `SELECT i.id,i.created_by,i.invoice_number AS "invoiceNumber",c.name AS "clientName",i.client_id AS "clientId",i.issue_date AS "issueDate",COALESCE(i.subtotal,0) AS subtotal,COALESCE(i.total,0) AS total,${numeric.map(k=>amount(k,fields[k])).join(',')},a.data->>'driver_name' AS "driverName",a.data->>'unload_location' AS "unloadLocation",${paid.map(k=>flag(k,fields[k])).join(',')} FROM invoices i INNER JOIN clients c ON c.id=i.client_id LEFT JOIN LATERAL (SELECT to_jsonb(x) AS data FROM invoice_accounting x WHERE x.invoice_id=i.id ORDER BY to_jsonb(x)->>'updated_at' DESC NULLS LAST,to_jsonb(x)->>'id' DESC LIMIT 1) a ON true`;
}
const netSql=`subtotal-payments-CASE WHEN "transportationPaid" THEN transportation ELSE 0 END-CASE WHEN "laborPaid" THEN labor ELSE 0 END-CASE WHEN "otherExpensesPaid" THEN "otherExpenses" ELSE 0 END`;
function normalRow(row){const result={...row};for(const key of ['subtotal','total',...numeric,'netIncome'])if(result[key]!=null)result[key]=Number(result[key]);for(const key of ['driverName','unloadLocation'])result[key]=result[key]||'';result.netIncome=accountingIncome(result);result.version=accountingVersion(result);return result;}
export function accountingQuery(user,params){const f=readFilters(params),values=[],bind=v=>{values.push(v);return '$'+values.length},where=['i.deleted_at IS NULL',recordWhere(user,'i',bind)];if(f.from)where.push(`i.issue_date>=${bind(f.from)}`);if(f.to)where.push(`i.issue_date<=${bind(f.to)}`);const filtered=[];if(f.q)filtered.push(`strpos(lower(concat_ws(' ',"invoiceNumber","clientName","driverName","unloadLocation")),lower(${bind(f.q)}))>0`);for(const key of ['clientId','driverName','unloadLocation']){const raw=params.get(key);if(raw){if(raw.length>250)throw fail(400,'Filter too long');if(key==='clientId'&&(!Number.isSafeInteger(Number(raw))||Number(raw)<=0))throw fail(400,'Invalid client');filtered.push(`"${key}"=${bind(key==='clientId'?Number(raw):raw)}`);}}const limit=bind(f.pageSize),offset=bind(f.offset);return {f,values,text:`WITH scoped AS (${rowSelect()} WHERE ${where.join(' AND ')}),filtered AS (SELECT *,${netSql} AS "netIncome" FROM scoped ${filtered.length?'WHERE '+filtered.join(' AND '):''}),paged AS (SELECT * FROM filtered ORDER BY id DESC LIMIT ${limit} OFFSET ${offset}) SELECT count(*) AS count,COALESCE(SUM(total),0) AS "totalInvoices",COALESCE(SUM(payments),0) AS payments,COALESCE(SUM(CASE WHEN NOT "transportationPaid" THEN transportation ELSE 0 END),0) AS "unpaidTransportation",COALESCE(SUM(CASE WHEN NOT "laborPaid" THEN labor ELSE 0 END),0) AS "unpaidLabor",COALESCE(SUM(CASE WHEN NOT "otherExpensesPaid" THEN "otherExpenses" ELSE 0 END),0) AS "unpaidOtherExpenses",COALESCE(SUM("netIncome"),0) AS "netIncome",COALESCE((SELECT json_agg(p ORDER BY id DESC) FROM paged p),'[]'::json) AS rows,COALESCE((SELECT json_agg(c) FROM (SELECT DISTINCT "clientId","clientName" FROM scoped ORDER BY "clientName") c),'[]'::json) AS clients,COALESCE((SELECT json_agg(v) FROM (SELECT DISTINCT "driverName" AS value FROM scoped WHERE COALESCE("driverName",'')<>'' ORDER BY value) v),'[]'::json) AS drivers,COALESCE((SELECT json_agg(v) FROM (SELECT DISTINCT "unloadLocation" AS value FROM scoped WHERE COALESCE("unloadLocation",'')<>'' ORDER BY value) v),'[]'::json) AS locations FROM filtered`};}
export async function readAccounting(pool,user,params){if(!canViewAccounting(user))throw fail(403,'Access denied');const q=accountingQuery(user,params);await accountingSchema(pool);const result=(await pool.query(q.text,q.values)).rows[0];const count=Number(result.count);return {...result,rows:result.rows.map(normalRow),count,page:q.f.page,pageSize:q.f.pageSize,pages:Math.max(1,Math.ceil(count/q.f.pageSize)),truncated:count>result.rows.length,fetchedAt:new Date().toISOString()};}
export async function updateAccounting(pool,input,user,enabled){if(!canViewAccounting(user))throw fail(403,'Access denied');if(!enabled)throw fail(409,'Saving disabled');const value=validateAccounting(input),db=await pool.connect();try{await db.query('BEGIN READ WRITE');const account=(await db.query('SELECT id,role,permissions,is_active,pending_approval,two_factor_email,two_factor_whatsapp FROM users WHERE id=$1 FOR SHARE',[user.id])).rows[0];if(!account?.is_active||account.pending_approval||account.two_factor_email||account.two_factor_whatsapp||!canViewAccounting(account))throw fail(403,'Access denied');const invoice=(await db.query('SELECT id,created_by,client_id FROM invoices WHERE id=$1 AND deleted_at IS NULL FOR UPDATE',[value.id])).rows[0];assertRecord({...account,id:user.id},invoice);const columns=await accountingSchema(db);const existing=(await db.query('SELECT invoice_id FROM invoice_accounting WHERE invoice_id=$1 FOR UPDATE',[value.id])).rows;if(existing.length>1)throw fail(409,'توجد سجلات حسابات مكررة؛ يلزم مراجعتها / Duplicate accounting records require review');const current=(await db.query(rowSelect()+' WHERE i.id=$1 AND i.deleted_at IS NULL',[value.id])).rows[0];if(!current)throw fail(404,'Invoice not found');const normalized=normalRow(current);if(normalized.version!==value.version)throw fail(409,'تغيّرت الحسابات؛ أغلق النموذج وافتحه مجددًا / Accounting changed; reopen the editor');const keys=Object.keys(fields),args=keys.map(k=>paid.includes(k)&&columns[fields[k]]!=='boolean'?(value.data[k]?1:0):value.data[k]);if(existing.length){const setters=keys.map((k,n)=>`${fields[k]}=$${n+1}`);if(columns.updated_at){if(/^timestamp/.test(columns.updated_at))setters.push('updated_at=clock_timestamp()');else if(/^(bigint|integer|numeric)/.test(columns.updated_at))setters.push('updated_at=(extract(epoch FROM clock_timestamp())*1000)::bigint');}args.push(value.id);await db.query(`UPDATE invoice_accounting SET ${setters.join(',')} WHERE invoice_id=$${args.length}`,args);}else{const names=['invoice_id',...keys.map(k=>fields[k])];const insertArgs=[value.id,...args];if(columns.updated_at&&/^timestamp/.test(columns.updated_at)){names.push('updated_at');insertArgs.push(new Date());}await db.query(`INSERT INTO invoice_accounting(${names.join(',')}) VALUES(${insertArgs.map((_,n)=>'$'+(n+1)).join(',')})`,insertArgs);}await db.query('COMMIT');return {id:value.id,saved:true};}catch(e){await db.query('ROLLBACK').catch(()=>{});throw e;}finally{db.release();}}
