import {receiptOwnerSql,recordScope,scopedReport} from './record-access.mjs';
import {reportSql,demoReport} from './report.mjs';
export const countsSql=`SELECT
 (SELECT count(*) FROM clients WHERE ($1::integer IS NULL OR id=$1)) AS clients,
 (SELECT count(*) FROM invoices WHERE deleted_at IS NULL AND ($1::integer IS NULL OR client_id=$1) AND ($2::text='' OR issue_date>=$2) AND ($3::text='' OR issue_date<=$3) AND status IN ('issued','paid')) AS invoices,
 (SELECT count(*) FROM invoices WHERE deleted_at IS NULL AND ($1::integer IS NULL OR client_id=$1) AND ($2::text='' OR issue_date>=$2) AND ($3::text='' OR issue_date<=$3) AND status='draft') AS draft_invoices,
 (SELECT count(*) FROM receipts WHERE deleted_at IS NULL AND ($1::integer IS NULL OR client_id=$1) AND ($2::text='' OR receipt_date>=$2) AND ($3::text='' OR receipt_date<=$3) AND status='issued') AS receipts,
 (SELECT count(*) FROM receipts WHERE deleted_at IS NULL AND ($1::integer IS NULL OR client_id=$1) AND ($2::text='' OR receipt_date>=$2) AND ($3::text='' OR receipt_date<=$3) AND status='draft') AS draft_receipts`;
export async function dashboard(pool,user,from,to){const scope=user.role==='client'?Number(user.client_id):null;const db=await pool.connect();try{await db.query('BEGIN ISOLATION LEVEL REPEATABLE READ READ ONLY');const report=scopedReport(reportSql,user,[scope,from,to,'',5,0]);const totals=(await db.query(report.text,report.values)).rows[0];const owner=user.role==='client'&&user.client_id?{all:true}:recordScope(user);let countText=owner.all?countsSql:countsSql.replaceAll('deleted_at IS NULL',`deleted_at IS NULL AND ${owner.denied?'FALSE':owner.column+'=$4'}`);if(user.role==='user')countText=countText.replaceAll('FROM receipts WHERE deleted_at IS NULL AND created_by=$4',`FROM receipts WHERE deleted_at IS NULL AND ${receiptOwnerSql('receipts','$4')}`);const counts=(await db.query(countText,owner.all||owner.denied?[scope,from,to]:[scope,from,to,owner.value])).rows[0];await db.query('COMMIT');return {...totals,counts,fetchedAt:new Date().toISOString()};}catch(e){await db.query('ROLLBACK').catch(()=>{});throw e;}finally{db.release();}}
export function demoDashboard(fixture,from,to){const inRange=(date)=>(!from||date>=from)&&(!to||date<=to);return {...demoReport(fixture.invoices,fixture.receipts,null,from,to,{offset:0,pageSize:5,q:''}),counts:{clients:fixture.clients.length,invoices:fixture.invoices.filter(r=>['issued','paid'].includes(r.status)&&inRange(r.issue_date)).length,draft_invoices:fixture.invoices.filter(r=>r.status==='draft'&&inRange(r.issue_date)).length,receipts:fixture.receipts.filter(r=>r.status==='issued'&&inRange(r.receipt_date)).length,draft_receipts:fixture.receipts.filter(r=>r.status==='draft'&&inRange(r.receipt_date)).length},fetchedAt:new Date().toISOString()};}
