const fail=message=>{throw Error(message);};
export function decimal(value,scale=2){const s=String(value??'0').trim();if(!/^\d+(\.\d+)?$/.test(s)||s.length>20)fail('Invalid non-negative number');const [whole,frac='']=s.split('.');if(frac.length>scale)fail('Too many decimal places');const n=BigInt(whole)*10n**BigInt(scale)+BigInt(frac.padEnd(scale,'0'));if(n>999999999999n)fail('Number too large');return n;}
const rounded=(value,divisor)=>(value+divisor/2n)/divisor;
export const cash=n=>`${n/100n}.${String(n%100n).padStart(2,'0')}`;
export function validateDraft(input){
if(!input||!['invoice','receipt'].includes(input.kind))fail('Invalid draft type');
const clientId=Number(input.clientId);if(!Number.isSafeInteger(clientId)||clientId<=0)fail('Select a client');
const date=String(input.date||'');if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||Number.isNaN(Date.parse(date))||new Date(date).toISOString().slice(0,10)!==date)fail('Invalid date');
const syncId=String(input.syncId||'');if(!/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(syncId))fail('Invalid draft identity');
const notes=String(input.notes||'').trim();if(notes.length>2000)fail('Notes too long');
const base={kind:input.kind,clientId,date,notes,status:'draft',source:'web',syncId,registered:false,number:null};
if(input.kind==='receipt'){const amount=decimal(input.amount);if(amount<=0n)fail('Receipt amount must be positive');const paymentMethod=String(input.paymentMethod||'cash');if(!['cash','bank_transfer','cheque'].includes(paymentMethod))fail('Invalid payment method');const invoiceId=input.invoiceId?Number(input.invoiceId):null;if(invoiceId!==null&&(!Number.isSafeInteger(invoiceId)||invoiceId<=0))fail('Invalid invoice');return {...base,amount:cash(amount),paymentMethod,invoiceId};}
if(!Array.isArray(input.items)||!input.items.length||input.items.length>100)fail('Invoice needs 1 to 100 items');
let subtotal=0n;const items=input.items.map(item=>{const description=String(item.description||'').trim();if(!description||description.length>500)fail('Invalid item description');const qty=decimal(item.quantity,3),price=decimal(item.unitPrice);if(qty<=0n)fail('Quantity must be positive');const total=rounded(qty*price,1000n);subtotal+=total;return {description,quantity:String(item.quantity),unitPrice:cash(price),total:cash(total)};});
if(subtotal>999999999999n)fail('Invoice total too large');const taxRate=decimal(input.taxRate);if(taxRate>10000n)fail('Tax rate exceeds 100');const taxAmount=rounded(subtotal*taxRate,10000n);const advance=decimal(input.advancePayment);if(advance>subtotal+taxAmount)fail('Advance exceeds invoice total');const shipmentRef=String(input.shipmentRef||'').trim(),billOfLading=String(input.billOfLading||'').trim();if(shipmentRef.length>100||billOfLading.length>100)fail('Reference too long');
const portOfEntry=String(input.portOfEntry||'').trim(),importerExporterName=String(input.importerExporterName||'').trim();if(portOfEntry.length>100||importerExporterName.length>200)fail('Shipment name too long');const packageCount=input.packageCount===''||input.packageCount==null?null:Number(input.packageCount);if(packageCount!==null&&(!Number.isSafeInteger(packageCount)||packageCount<0||packageCount>2147483647))fail('Invalid package count');const shipmentWeight=input.shipmentWeight===''||input.shipmentWeight==null?null:String(input.shipmentWeight);if(shipmentWeight!==null)decimal(shipmentWeight,3);const dueDate=String(input.dueDate||'');if(dueDate&&(!/^\d{4}-\d{2}-\d{2}$/.test(dueDate)||Number.isNaN(Date.parse(dueDate))||new Date(dueDate).toISOString().slice(0,10)!==dueDate||dueDate<date))fail('Invalid due date');
const salesManId=input.salesManId==null||input.salesManId===''?null:Number(input.salesManId);if(salesManId!==null&&(!Number.isSafeInteger(salesManId)||salesManId<=0))fail('Invalid representative');const requestedStatus=input.status==null?null:String(input.status);if(requestedStatus!==null&&!['draft','issued','paid','cancelled'].includes(requestedStatus))fail('Invalid invoice status');
return {...base,salesManId,requestedStatus,portOfEntry,importerExporterName,packageCount,shipmentWeight,dueDate,items,taxRate:cash(taxRate),subtotal:cash(subtotal),taxAmount:cash(taxAmount),grossTotal:cash(subtotal+taxAmount),advancePayment:cash(advance),remaining:cash(subtotal+taxAmount-advance),shipmentRef,billOfLading};}
