import {recordWhere} from './record-access.mjs';
export function readFilters(params){
const number=(key,fallback,max)=>{const raw=params.get(key);if(raw===null)return fallback;if(!/^\d+$/.test(raw))throw Error('Invalid pagination');const n=Number(raw);if(n<1||n>max||!Number.isSafeInteger(n))throw Error('Invalid pagination');return n;};
const page=number('page',1,1000000),pageSize=number('pageSize',100,500),q=(params.get('q')||'').trim();if(q.length>200)throw Error('Search too long');const from=params.get('from')||'',to=params.get('to')||'';
const valid=x=>!x||(/^\d{4}-\d{2}-\d{2}$/.test(x)&&!Number.isNaN(Date.parse(x))&&new Date(x).toISOString().slice(0,10)===x);if(!valid(from)||!valid(to)||(from&&to&&from>to))throw Error('Invalid date range');return {page,pageSize,q,from,to,offset:(page-1)*pageSize};}
export function listQuery(kind,user,f,includeRemote=false){
const configs={clients:{table:'clients',cols:'t.id,t.name,t.email,t.phone',order:'t.name,t.id',search:['t.name','t.phone','t.email','t.id::text']},invoices:{table:'invoices',cols:'t.id,t.client_id,c.name AS client_name,t.invoice_number,t.issue_date,t.status,t.subtotal,t.tax_amount,t.total,t.advance_payment,t.shipment_ref,t.bill_of_lading',order:'t.issue_date DESC,t.id DESC',date:'t.issue_date',search:['t.invoice_number','c.name','t.shipment_ref','t.bill_of_lading','t.status']},receipts:{table:'receipts',cols:'t.id,t.client_id,c.name AS client_name,t.invoice_id,t.receipt_number,t.receipt_date,t.status,t.amount,t.payment_method',order:'t.receipt_date DESC,t.id DESC',date:'t.receipt_date',search:['t.receipt_number','c.name','t.status','t.payment_method']},templates:{table:'invoice_item_templates',cols:'t.id,t.item_code,t.description,t.default_unit_price',order:'t.id',search:['t.item_code','t.description']}};
const c=configs[kind];if(!c)throw Error('Invalid list');
if(kind==='invoices'&&includeRemote){c.table=`(SELECT id::text AS id,created_by,client_id,invoice_number,issue_date::text AS issue_date,status,subtotal::numeric AS subtotal,tax_amount::numeric AS tax_amount,total::numeric AS total,advance_payment::numeric AS advance_payment,shipment_ref,bill_of_lading,deleted_at FROM invoices
UNION ALL SELECT 'web:'||sync_id::text,COALESCE(NULLIF(payload->>'salesManId','')::integer,created_by),client_id,invoice_number,payload->>'date','draft',(payload->>'subtotal')::numeric,(payload->>'taxAmount')::numeric,(payload->>'remaining')::numeric,(payload->>'advancePayment')::numeric,payload->>'shipmentRef',payload->>'billOfLading',NULL::timestamptz FROM ledger_remote_invoice_drafts d WHERE NOT EXISTS(SELECT 1 FROM invoices i WHERE i.invoice_number=d.invoice_number))`;}
const where=[],values=[];const bind=v=>{values.push(v);return '$'+values.length;};
if(c.date)where.push('t.deleted_at IS NULL',recordWhere(user,'t',bind,kind==='receipts'?'receipt':'invoice'));if(kind==='clients'&&user.role==='client')where.push(`${kind==='clients'?'t.id':'t.client_id'}=${bind(user.client_id)}`);
if(f.q){const p=bind(f.q);where.push(`strpos(lower(concat_ws(' ',${c.search.join(',')})),lower(${p}))>0`);}if(c.date&&f.from)where.push(`${c.date}>=${bind(f.from)}`);if(c.date&&f.to)where.push(`${c.date}<=${bind(f.to)}`);
const limit=bind(f.pageSize),offset=bind(f.offset);
return {text:`WITH filtered AS (SELECT ${c.cols},row_number() OVER (ORDER BY ${c.order}) AS position FROM ${c.table} t ${c.date?'LEFT JOIN clients c ON c.id=t.client_id':''} ${where.length?'WHERE '+where.join(' AND '):''}), paged AS (SELECT * FROM filtered ORDER BY position LIMIT ${limit} OFFSET ${offset}) SELECT (SELECT count(*) FROM filtered) AS count,COALESCE((SELECT json_agg(p ORDER BY position) FROM paged p),'[]'::json) AS rows`,values};}
export function demoList(rows,f){const matches=rows.filter(r=>(!f.q||Object.values(r).join(' ').toLowerCase().includes(f.q.toLowerCase()))&&(!f.from||!(r.issue_date||r.receipt_date)||(r.issue_date||r.receipt_date)>=f.from)&&(!f.to||!(r.issue_date||r.receipt_date)||(r.issue_date||r.receipt_date)<=f.to));return {count:matches.length,rows:matches.slice(f.offset,f.offset+f.pageSize)};}
