import test from 'node:test';import assert from 'node:assert/strict';
import {canViewAccounting,accountingIncome,accountingVersion,validateAccounting,accountingQuery,accountingSchema,updateAccounting} from '../accounting.mjs';
import {validateSettings} from '../remote-settings.mjs';import {actionAllowed} from '../action-policy.mjs';
const user={id:8,role:'user',permissions:{canViewAccounting:true}};
const row={id:2,created_by:8,subtotal:1000,payments:100,transportation:200,labor:50,otherExpenses:25,driverName:'Driver',unloadLocation:'Warehouse',transportationPaid:false,laborPaid:true,otherExpensesPaid:false};
const input={id:2,version:accountingVersion(row),payments:'100',transportation:'200',labor:'50',otherExpenses:'25',driverName:'Driver',unloadLocation:'Warehouse',transportationPaid:false,laborPaid:true,otherExpensesPaid:false};
const cols=['invoice_id','payments','transportation','labor','other_expenses','driver_name','unload_location','transportation_paid','labor_paid','other_expenses_paid'];
function fake({owner=8,stale=false,duplicates=false,insert=false,integerFlags=false,revoked=false}={}){const calls=[];const db={release(){},async query(sql,v){calls.push({sql,v});if(sql.startsWith('SELECT id,role'))return {rows:[{...user,id:8,is_active:true,role:revoked?'client':'user'}]};if(sql.startsWith('SELECT id,created_by'))return {rows:[{id:2,created_by:owner}]};if(sql.includes('FROM pg_attribute'))return {rows:cols.map(name=>({name,type:name.endsWith('_paid')?(integerFlags?'integer':'boolean'):'numeric'}))};if(sql.startsWith('SELECT invoice_id'))return {rows:insert?[]:duplicates?[{invoice_id:2},{invoice_id:2}]:[{invoice_id:2}]};if(sql.startsWith('SELECT i.id'))return {rows:[{...row,payments:stale?101:100}]};return {rows:[]};}};return {calls,pool:{connect:async()=>db}};}
test('income matches Desktop subtotal minus payments and only paid expenses, including negative income',()=>{assert.equal(accountingIncome(row),850);assert.equal(accountingIncome({...row,transportationPaid:true,otherExpensesPaid:true}),625);assert.equal(accountingIncome({...row,subtotal:50,advance_payment:999,tax_amount:999}),-100);});
test('clients cannot view accounting and Desktop accounting permission remains required',()=>{assert.equal(canViewAccounting({role:'admin'}),true);assert.equal(canViewAccounting(user),true);assert.equal(canViewAccounting({role:'supervisor',permissions:{canViewAccounting:false}}),false);assert.equal(canViewAccounting({role:'client',permissions:{canViewAccounting:true}}),false);});
test('expense validation rejects invalid money, payment flags and truncated forms',()=>{for(const payments of ['-1','NaN','1.001','10000000000'])assert.throws(()=>validateAccounting({...input,payments}),{status:400});assert.throws(()=>validateAccounting({...input,transportationPaid:'true'}),{status:400});assert.throws(()=>validateAccounting({...input,driverName:undefined}),{status:400});assert.equal(validateAccounting(input).data.payments,'100.00');});
test('filters are bound and owner scope applies before totals and pagination',()=>{const q=accountingQuery(user,new URLSearchParams({q:"x' OR 1=1",from:'2026-10-01',to:'2026-10-08',clientId:'3',driverName:'Driver',unloadLocation:'Warehouse',pageSize:'10'}));assert.match(q.text,/i.created_by=\$1/);assert.equal(q.values[0],8);assert.ok(!q.text.includes("x' OR 1=1"));assert.ok(q.values.includes("x' OR 1=1"));assert.match(q.text,/SUM\("netIncome"\)/);assert.match(q.text,/SUM\(total\),0\) AS "totalInvoices"/);assert.match(q.text,/FROM filtered$/);assert.throws(()=>accountingQuery(user,new URLSearchParams('clientId=bad')),{status:400});});
test('existing accounting save locks, revalidates scope and commits all fields',async()=>{const f=fake();assert.deepEqual(await updateAccounting(f.pool,input,user,true),{id:2,saved:true});const update=f.calls.find(c=>c.sql.startsWith('UPDATE invoice_accounting'));assert.equal(update.v.at(-1),2);assert.equal(update.v[6],false);assert.ok(f.calls.findIndex(c=>c.sql.startsWith('SELECT invoice_id'))<f.calls.findIndex(c=>c.sql.startsWith('SELECT i.id')));assert.equal(f.calls.at(-1).sql,'COMMIT');});
test('new accounting row inserts once and integer payment flags retain storage representation',async()=>{const f=fake({insert:true,integerFlags:true});await updateAccounting(f.pool,input,user,true);const insert=f.calls.find(c=>c.sql.startsWith('INSERT INTO invoice_accounting'));assert.equal(insert.v[0],2);assert.equal(insert.v[7],0);assert.equal(insert.v[8],1);assert.ok(!insert.sql.includes('updated_at'));});
test('stale, duplicate, revoked and foreign invoice edits roll back without writes',async()=>{for(const options of [{stale:true},{duplicates:true},{revoked:true},{owner:9}]){const f=fake(options);await assert.rejects(updateAccounting(f.pool,input,user,true));assert.ok(f.calls.some(c=>c.sql==='ROLLBACK'));assert.equal(f.calls.some(c=>/^(UPDATE|INSERT)/.test(c.sql)),false);}});
test('missing Online accounting schema reports readiness and never alters tables',async()=>{const calls=[];await assert.rejects(accountingSchema({query:async sql=>{calls.push(sql);return {rows:[]};}}),{status:409});assert.ok(calls.every(sql=>sql.startsWith('SELECT')));await assert.rejects(updateAccounting(null,input,user,false),{status:409});});
test('accounting page and write action can be limited by admin settings',()=>{const settings=validateSettings({startPage:'accounting',pageSize:10,datePeriod:'month',showClock:true,pageAccess:{8:['accounting']},userActions:{8:{accountingEdit:false}}});assert.equal(settings.startPage,'accounting');assert.equal(actionAllowed(settings,user,'accountingEdit'),false);assert.equal(actionAllowed(settings,{role:'admin'},'accountingEdit'),true);});

test('version is stable across PostgreSQL scalar and JSON numeric IDs',()=>{const row={id:23,created_by:7,subtotal:650,payments:0,transportation:0,labor:0,otherExpenses:0,driverName:'',unloadLocation:'',transportationPaid:false,laborPaid:false,otherExpensesPaid:false};assert.equal(accountingVersion(row),accountingVersion({...row,id:'23',created_by:'7',subtotal:'650.00',payments:'0.00',driverName:null}));assert.notEqual(accountingVersion(row),accountingVersion({...row,payments:550}));});
