import test from 'node:test';import assert from 'node:assert/strict';import {readInvoiceEdit,updateInvoice,canEditInvoice,getShipmentBase} from '../invoice-edit.mjs';
const user={id:1,role:'admin'},uuid='a4483e87-3982-4e11-9cb6-7eeae233243e';
const invoice={id:7,invoice_number:'INV-2026-0010',client_id:1,issue_date:'2026-10-07',due_date:null,status:'issued',subtotal:'100.00',tax_rate:'0.00',tax_amount:'0.00',total:'90.00',advance_payment:'10.00',shipment_ref:'12345678901234-1',bill_of_lading:'BL',created_by:4,created_source:'desktop',sync_id:null,updated_at:'2026-10-07T12:00:00Z',edit_paid:'50.00',edit_receipts:'1',edit_items:[{id:10,description:'Old',quantity:'1',unit_price:'100.00',total:'100.00'}]};
function fake(options={}){const state={row:structuredClone(invoice),account:{role:'admin',is_active:true},requests:new Map(),...options};let snapshot;const calls=[];const query=async(sql,values=[])=>{calls.push({sql,values});let rows=[];
 if(sql==='BEGIN READ WRITE')snapshot={row:structuredClone(state.row),requests:new Map(state.requests)};
 else if(sql==='ROLLBACK'){state.row=snapshot.row;state.requests=snapshot.requests;}
 else if(sql.startsWith('SELECT role'))rows=[state.account];
 else if(sql.startsWith('SELECT created_by'))rows=state.requests.has(values[0])?[state.requests.get(values[0])]:[];
 else if(sql.startsWith('SELECT i.*'))rows=state.row?[structuredClone(state.row)]:[];
 else if(sql.startsWith('SELECT id FROM invoices'))rows=options.duplicateDeclaration?[{id:7},{id:8}]:[{id:state.row.id}];
 else if(sql.startsWith('SELECT id FROM users'))rows=options.missingRepresentative?[]:[{id:values[0]}];
 else if(sql.startsWith('SELECT id FROM clients'))rows=options.missingClient?[]:[{id:values[0]}];
 else if(sql.startsWith('UPDATE invoices')){state.row={...state.row,client_id:values[0],issue_date:values[1],subtotal:values[3],tax_amount:values[5],total:values[6],shipment_ref:values[8],advance_payment:values[14],status:values[15],created_by:values[17],updated_at:'new'};}
 else if(sql.startsWith('DELETE FROM invoice_items'))state.row.edit_items=[];
 else if(sql.startsWith('INSERT INTO invoice_items')){if(options.itemFailure)throw Error('item save failure');state.row.edit_items.push({description:values[1],quantity:values[2],unit_price:values[3],total:values[4]});}
 else if(sql.startsWith('INSERT INTO ledger_remote_invoice_edit_requests'))state.requests.set(values[0],{created_by:values[1],request_hash:values[2],result:JSON.parse(values[4])});
 return {rows};};return {state,calls,query,connect:async()=>({query,release(){state.released=true;}})};}
async function input(db,extra={}){const result=await readInvoiceEdit(db,7,user);return {id:7,version:result.version,originalShipmentRef:result.invoice.shipment_ref,syncId:uuid,clientId:1,date:'2026-10-07',taxRate:'0',advancePayment:'10',shipmentRef:'12345678901234-1',items:[{description:'Changed',quantity:'2',unitPrice:'40'}],...extra};}
test('updates original invoice and items, preserves immutable identity/creator and payment state',async()=>{const db=fake(),data=await input(db);const r=await updateInvoice(db,data,user,true);assert.equal(r.id,7);assert.equal(r.number,invoice.invoice_number);assert.equal(db.state.row.invoice_number,invoice.invoice_number);assert.equal(db.state.row.created_by,4);assert.equal(db.state.row.created_source,'desktop');assert.equal(db.state.row.sync_id,null);assert.equal(db.state.row.status,'issued');assert.equal(db.state.row.total,'70.00');assert.equal(db.state.row.shipment_ref,'12345678901234-1');assert.equal(db.state.row.edit_items[0].total,'80.00');const update=db.calls.find(c=>c.sql.startsWith('UPDATE invoices'));assert.ok(!/invoice_number=|sync_id=|created_source=/.test(update.sql));assert.ok(db.calls.some(c=>c.sql==='COMMIT'));});
test('paid invoice recalculates to issued; draft never becomes issued',async()=>{for(const status of ['paid','draft']){const db=fake();db.state.row.status=status;await updateInvoice(db,await input(db),user,true);assert.equal(db.state.row.status,status==='draft'?'draft':'issued');}const db=fake();await updateInvoice(db,await input(db,{items:[{description:'Full payment',quantity:'1',unitPrice:'60'}]}),user,true);assert.equal(db.state.row.status,'paid');});
test('rejects totals below receipts, linked-client changes and stale item edits before writing',async()=>{for(const kind of ['total','client','stale','cancelled']){const db=fake();const data=await input(db);if(kind==='total')data.items[0].unitPrice='20';if(kind==='client')data.clientId=2;if(kind==='stale')db.state.row.edit_items[0].description='Other edit';if(kind==='cancelled')db.state.row.status='cancelled';await assert.rejects(updateInvoice(db,data,user,true),{status:409});assert.ok(!db.calls.some(c=>c.sql.startsWith('UPDATE invoices')));assert.ok(db.calls.some(c=>c.sql==='ROLLBACK'));}});
test('item failure rolls back complete invoice and request log',async()=>{const db=fake({itemFailure:true});const before=structuredClone(db.state.row);await assert.rejects(updateInvoice(db,await input(db),user,true),/item save failure/);assert.deepEqual(db.state.row,before);assert.equal(db.state.requests.size,0);assert.equal(db.state.released,true);});
test('same edit safely replays; changed retry input conflicts',async()=>{const db=fake();const data=await input(db);await updateInvoice(db,data,user,true);const writes=db.calls.filter(c=>c.sql.startsWith('UPDATE invoices')).length;assert.equal((await updateInvoice(db,data,user,true)).replayed,true);assert.equal(db.calls.filter(c=>c.sql.startsWith('UPDATE invoices')).length,writes);await assert.rejects(updateInvoice(db,{...data,notes:'different'},user,true),{status:409});});
test('client, disabled writes, revoked permissions, malformed IDs and versions denied',async()=>{assert.equal(canEditInvoice({role:'client'}),false);assert.equal(canEditInvoice({role:'user',permissions:{canEditInvoices:true}}),true);await assert.rejects(readInvoiceEdit(null,7,{role:'client'}),{status:403});await assert.rejects(updateInvoice(null,{},user,false),{status:409});await assert.rejects(updateInvoice(null,{id:'bad'},user,true),{status:400});const db=fake({account:{role:'user',permissions:{},is_active:true}});await assert.rejects(updateInvoice(db,await input(db),user,true),{status:403});});
test('web identity resolves canonical invoice; existing number unchanged',async()=>{const db=fake();db.state.row.created_source='web';db.state.row.sync_id=uuid;db.state.row.invoice_number='INV-W-2026-0001';const read=await readInvoiceEdit(db,'web:'+uuid,user);assert.equal(read.invoice.id,7);const data=await input(db,{id:'web:'+uuid});await updateInvoice(db,data,user,true);assert.equal(db.state.row.invoice_number,'INV-W-2026-0001');assert.equal(db.state.row.sync_id,uuid);assert.ok(db.calls.some(c=>c.sql.includes("to_jsonb(i)->>'sync_id'=$1")));});

test('full original declaration suffix identifies target; wrong original reference rejected',async()=>{const db=fake();await updateInvoice(db,await input(db),user,true);assert.equal(db.state.row.shipment_ref,'12345678901234-1');for(const originalShipmentRef of ['12345678901234/2','12345678901234 (1)','92345678901234']){const other=fake();await assert.rejects(updateInvoice(other,await input(other,{originalShipmentRef}),user,true),{status:409});assert.ok(!other.calls.some(c=>c.sql.startsWith('UPDATE invoices')));}const ambiguous=fake({duplicateDeclaration:true});await assert.rejects(updateInvoice(ambiguous,await input(ambiguous),user,true),{status:409});});

test('selected representative persists, actor and original owner remain in audit, invalid selection rolls back',async()=>{
 const db=fake();await updateInvoice(db,await input(db,{salesManId:9}),user,true);assert.equal(db.state.row.created_by,9);
 const audit=db.calls.find(c=>c.sql.startsWith('INSERT INTO ledger_remote_invoice_edit_requests'));assert.equal(audit.values[1],user.id);assert.equal(JSON.parse(audit.values[5]).created_by,4);
 const bad=fake({missingRepresentative:true});await assert.rejects(updateInvoice(bad,await input(bad,{salesManId:9}),user,true),{status:400});assert.equal(bad.state.row.created_by,4);
});
test('status selection issues drafts, permits reverting uncollected invoices and safe cancellation',async()=>{
 for(const [before,after]of [['draft','issued'],['issued','draft'],['issued','cancelled']]){const db=fake();Object.assign(db.state.row,{status:before,edit_paid:'0.00',edit_receipts:'0',advance_payment:'0.00'});const result=await updateInvoice(db,await input(db,{status:after,advancePayment:'0'}),user,true);assert.equal(result.status,after);assert.equal(db.state.row.status,after);}
});
test('paid selection requires actual settlement; linked receipts block draft/cancelled transitions',async()=>{
 for(const status of ['paid','draft','cancelled']){const db=fake();await assert.rejects(updateInvoice(db,await input(db,{status}),user,true),{status:409});assert.ok(!db.calls.some(c=>c.sql.startsWith('UPDATE invoices')));}
 const settled=fake();await updateInvoice(settled,await input(settled,{status:'paid',items:[{description:'Paid',quantity:'1',unitPrice:'60'}]}),user,true);assert.equal(settled.state.row.status,'paid');
 const advanced=fake();Object.assign(advanced.state.row,{edit_paid:'0.00',edit_receipts:'0'});await assert.rejects(updateInvoice(advanced,await input(advanced,{status:'cancelled'}),user,true),{status:409});
});
test('representative/status changes participate in request identity and permission checks',async()=>{
 const db=fake();const data=await input(db,{salesManId:9,status:'issued'});await updateInvoice(db,data,user,true);await assert.rejects(updateInvoice(db,{...data,salesManId:10},user,true),{status:409});
 for(const extra of [{salesManId:-1},{salesManId:'bad'},{status:'unknown'}]){const other=fake();await assert.rejects(updateInvoice(other,await input(other,extra),user,true),{status:400});}
});
