import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {deleteInvoice,readInvoicePayment,canDeleteInvoice} from '../invoice-actions.mjs';
import {saveInvoice} from '../save-invoice.mjs';
const admin={id:7,role:'admin'};
const payment={kind:'receipt',payNow:true,syncId:'46fc7e57-0d92-4ca3-9359-50c7cabc22d3',clientId:1,invoiceId:2,date:'2026-10-08',amount:'80',paymentMethod:'cash'};
function database({failAudit=false,denied=false,paid=0,status='issued'}={}){
 let state={invoice:{id:2,client_id:1,invoice_number:'INV-2026-0036',sync_id:payment.syncId,status,subtotal:100,tax_amount:0,advance_payment:20,deleted_at:null,created_by:9},receipts:[{id:3,invoice_id:2,status:'issued',amount:paid,deleted_at:null}],markers:[],saved:null,counter:0};let backup;const calls=[];
 const db={release(){},async query(sql,v=[]){calls.push({sql,v});const rows=x=>({rows:x});
 if(sql==='BEGIN READ WRITE'){backup=structuredClone(state);return rows([]);}if(sql==='ROLLBACK'){state=backup;return rows([]);}if(sql==='COMMIT'||sql.startsWith('CREATE TABLE')||sql.includes('pg_advisory_xact_lock'))return rows([]);
 if(sql.startsWith('SELECT role'))return rows([{role:denied?'client':'admin',is_active:true,display_name:'Actor'}]);
 if(sql.startsWith('SELECT * FROM invoices'))return rows(state.invoice.deleted_at&&sql.includes('deleted_at IS NULL')?[]:[structuredClone(state.invoice)]);
 if(sql.startsWith('SELECT * FROM receipts'))return rows(structuredClone(state.receipts));
 if(sql.startsWith('SELECT COALESCE'))return rows([{paid:state.receipts.filter(r=>r.status==='issued'&&!r.deleted_at).reduce((n,r)=>n+Number(r.amount),0)}]);
 if(sql.startsWith('SELECT created_by'))return rows(state.saved?[state.saved]:[]);
 if(sql.startsWith('SELECT id,created_by,client_id FROM receipts')||sql.startsWith('SELECT id FROM receipts'))return rows(state.receipts.filter(r=>Number(r.amount)>0&&!r.deleted_at&&['draft','issued'].includes(r.status)).map(r=>({id:r.id})));
 if(sql.startsWith('SELECT id FROM invoices'))return rows([{id:2}]);
 if(sql.startsWith('SELECT id,name'))return rows([{id:1,name:'Customer'}]);
 if(sql.startsWith('INSERT INTO ledger_remote_counters'))return rows([{last_number:++state.counter}]);
 if(sql.startsWith('SELECT id,sync_id'))return rows([]);
 if(sql.startsWith('SELECT id,invoice_number,status'))return rows([{...state.invoice,remaining:100-20-state.receipts.filter(r=>r.status==='issued'&&!r.deleted_at).reduce((n,r)=>n+Number(r.amount),0)}]);
 if(sql.startsWith('INSERT INTO receipts')){state.receipts.push({id:4,invoice_id:v[2],amount:v[3],status:'draft',deleted_at:null,created_by:v[7]});return rows([{id:4}]);}
 if(sql.startsWith("UPDATE receipts SET status='issued'")){state.receipts.find(r=>r.id===v[0]).status='issued';return rows([]);}
 if(sql.startsWith('UPDATE receipts SET deleted_at')){for(const r of state.receipts){r.deleted_at||=v[0];r.status='cancelled';}return rows([]);}
 if(sql.startsWith('UPDATE invoices SET status=$1')){state.invoice.status=v[0];return rows([]);}
 if(sql.startsWith('UPDATE invoices SET deleted_at')){state.invoice.deleted_at=v[0];state.invoice.status='cancelled';return rows([]);}
 if(sql.startsWith('INSERT INTO ledger_document_sync_changes')){state.markers.push({kind:v[0],id:v[1],change:v[2]});return rows([]);}
 if(sql.startsWith('INSERT INTO ledger_remote_delete_events')){if(failAudit)throw Error('Audit failed');return rows([]);}
 if(sql.startsWith('INSERT INTO ledger_remote_receipt_drafts')){assert.equal(JSON.parse(v[5]).status,'draft','Remote draft payload constraint must hold');if(failAudit)throw Error('Audit failed');state.saved={created_by:v[3],request_hash:v[4],payload:JSON.parse(v[5])};return rows([]);}
 throw Error('Unexpected query: '+sql);
 }};return {connect:async()=>db,query:db.query,get state(){return state;},calls};
}
test('delete cancels receipts before invoice, retains identities and commits matching Desktop tombstones',async()=>{const db=database();const result=await deleteInvoice(db,{id:2,number:'INV-2026-0036'},admin,true);assert.equal(result.status,'cancelled');assert.equal(db.state.invoice.created_by,9);assert.equal(db.state.invoice.invoice_number,'INV-2026-0036');assert.ok(db.state.invoice.deleted_at);assert.equal(db.state.receipts[0].status,'cancelled');assert.deepEqual(db.state.markers.map(m=>m.kind),['receipt','invoice']);assert.equal(db.state.markers[0].change,db.state.markers[1].change);assert.ok(db.calls.findIndex(c=>c.sql.startsWith('UPDATE receipts'))<db.calls.findIndex(c=>c.sql.startsWith('UPDATE invoices')));assert.equal((await deleteInvoice(db,{id:2,number:'INV-2026-0036'},admin,true)).replayed,true);assert.equal(db.state.markers.length,2);});
test('audit failure rolls back entire invoice/receipt deletion and markers',async()=>{const db=database({failAudit:true});await assert.rejects(deleteInvoice(db,{id:2,number:'INV-2026-0036'},admin,true),/Audit failed/);assert.equal(db.state.invoice.status,'issued');assert.equal(db.state.invoice.deleted_at,null);assert.equal(db.state.receipts[0].deleted_at,null);assert.equal(db.state.markers.length,0);});
test('delete checks both permissions, refreshed account, number and enabled writes',async()=>{assert.equal(canDeleteInvoice({role:'user',permissions:{canEditInvoices:true}}),false);for(const [db,input,user,enabled,status]of [[database(),{id:2,number:'x'},admin,true,409],[database({denied:true}),{id:2,number:'INV-2026-0036'},admin,true,403],[null,{id:2},admin,false,409],[null,{id:2},{role:'client'},true,403],[null,{id:'bad',number:'x'},admin,true,400]])await assert.rejects(deleteInvoice(db,input,user,enabled),{status});});
test('Web UUID resolves canonical invoice for deletion without recreating it',async()=>{const db=database();await deleteInvoice(db,{id:'web:'+payment.syncId,number:'INV-2026-0036'},admin,true);const select=db.calls.find(c=>c.sql.startsWith('SELECT * FROM invoices'));assert.deepEqual(select.v,[null,payment.syncId]);});
test('payment reads actual remaining and rejects drafts, fully paid and client accounts',async()=>{assert.equal((await readInvoicePayment(database(),2,admin,true)).invoice.remaining,'80.00');assert.equal((await readInvoicePayment(database({paid:80}),2,admin,true)).existingReceiptId,3);await assert.rejects(readInvoicePayment(database({status:'draft'}),2,admin,true),{status:409});await assert.rejects(readInvoicePayment(null,2,{role:'client'},true),{status:403});});
test('confirmed payment issues one receipt and settles invoice atomically; retry does not duplicate',async()=>{const db=database();const result=await saveInvoice(db,payment,admin);assert.equal(result.draft.status,'issued');assert.equal(db.state.saved.payload.status,'draft');assert.equal(db.state.saved.payload.paymentStatus,'issued');assert.equal(result.draft.number,'REC-W-2026-0001');assert.equal(db.state.invoice.status,'paid');assert.equal(db.state.receipts[1].created_by,7);const replay=await saveInvoice(db,payment,admin);assert.equal(replay.replayed,true);assert.equal(replay.draft.status,'issued');assert.equal(db.state.receipts.length,2);assert.equal(db.state.counter,1);await assert.rejects(saveInvoice(db,{...payment,amount:'70'},admin),{status:409});});
test('partial payment leaves invoice issued; audit failure and overpayment leave no receipt',async()=>{const partial=database();await saveInvoice(partial,{...payment,amount:'30'},admin);assert.equal(partial.state.invoice.status,'issued');for(const options of [{failAudit:true},{paid:1},{status:'cancelled'},{denied:true}]){const db=database(options);await assert.rejects(saveInvoice(db,payment,admin));assert.equal(db.state.receipts.length,1);assert.equal(db.state.counter,0);assert.equal(db.state.invoice.status,options.status||'issued');}});
test('payment mode participates in request identity and requires linked receipt',async()=>{await assert.rejects(saveInvoice(null,{...payment,invoiceId:null},admin),{status:400});await assert.rejects(saveInvoice(null,{...payment,payNow:'yes'},admin),{status:400});const db=database();await saveInvoice(db,payment,admin);await assert.rejects(saveInvoice(db,{...payment,payNow:false},admin),{status:409});});
test('invoice actions expose confirmations and payment form preserves linked client/invoice',async()=>{const app=await readFile(new URL('../public/app.js',import.meta.url),'utf8'),ui=await readFile(new URL('../public/draft-ui.js',import.meta.url),'utf8');assert.match(app,/me\.access\.payInvoice/);assert.match(app,/me\.access\.deleteInvoice/);assert.match(app,/confirm\(t\('سيتم تحويل الفاتورة/);assert.match(ui,/input\.payNow=true/);assert.match(ui,/draft-client'\)\.disabled=true/);assert.match(ui,/draft-invoice'\)\.disabled=true/);assert.match(ui,/تأكيد الدفع وإصدار السند/);});

test('Pay opens first linked receipt, and stale new payment cannot create a second receipt',async()=>{const db=database({paid:30});assert.equal((await readInvoicePayment(db,2,admin,true)).existingReceiptId,3);await assert.rejects(saveInvoice(db,{...payment,amount:'20'},admin),{status:409});assert.equal(db.state.receipts.length,1);assert.equal(db.state.saved,null);});

test('receipt delete cancels only selected receipt and atomically recalculates parent; audit failure rolls back',async()=>{
 const {deleteReceipt}=await import('../invoice-actions.mjs');
 for(const failAudit of [false,true]){
 let state={receipt:{id:8,receipt_number:'REC-W-2026-0002',invoice_id:2,status:'issued',deleted_at:null},invoiceStatus:'paid',marker:false},backup;const calls=[];
 const db={release(){},async query(sql,v=[]){calls.push(sql);if(sql==='BEGIN READ WRITE'){backup=structuredClone(state);return {rows:[]};}if(sql==='ROLLBACK'){state=backup;return {rows:[]};}if(sql==='COMMIT'||sql.startsWith('CREATE TABLE'))return {rows:[]};if(sql.startsWith('SELECT role'))return {rows:[{role:'admin',is_active:true}]};if(sql.startsWith('SELECT id,invoice_id'))return {rows:[state.receipt]};if(sql.startsWith('SELECT id FROM invoices'))return {rows:[{id:2}]};if(sql.startsWith('SELECT * FROM receipts'))return {rows:[{...state.receipt}]};if(sql.startsWith('UPDATE receipts')){assert.match(sql,/WHERE id=\$1/);assert.equal(v[0],8);state.receipt.status='cancelled';state.receipt.deleted_at=new Date();return {rows:[]};}if(sql.startsWith('INSERT INTO ledger_document_sync_changes')){state.marker=true;return {rows:[]};}if(sql.startsWith('UPDATE invoices')){assert.match(sql,/status IN \('issued','paid'\)/);state.invoiceStatus='issued';return {rows:[]};}if(sql.startsWith('INSERT INTO ledger_remote_receipt_delete_events')){if(failAudit)throw Error('Audit failed');return {rows:[]};}throw Error(sql);}};
 const pool={connect:async()=>db},input={id:8,number:'REC-W-2026-0002'};
 if(failAudit){await assert.rejects(deleteReceipt(pool,input,admin,true),/Audit failed/);assert.equal(state.receipt.status,'issued');assert.equal(state.invoiceStatus,'paid');assert.equal(state.marker,false);}else{await deleteReceipt(pool,input,admin,true);assert.equal(state.receipt.status,'cancelled');assert.equal(state.invoiceStatus,'issued');assert.equal(state.marker,true);assert.equal((await deleteReceipt(pool,input,admin,true)).replayed,true);}
 }
});
