import test from 'node:test';import assert from 'node:assert/strict';import {issueDocument,canIssue,invoiceStatus,validateReceiptIssue} from '../issue-document.mjs';
const admin={id:7,role:'admin'},invoiceBase={id:2,client_id:1,invoice_number:'INV-2026-0026',status:'draft',subtotal:'100.00',tax_amount:'0.00',advance_payment:'20.00',shipment_ref:'12345678901234 (1)',created_by:9,sync_id:'unchanged'},receiptBase={id:3,client_id:1,invoice_id:2,receipt_number:'REC-W-2026-0001',amount:'80.00',status:'draft',created_by:9};
function fake({invoice={...invoiceBase},receipt={...receiptBase},paid=0,denied=false,failAudit=false}={}){let backup;const calls=[];const db={release(){},async query(sql,v=[]){calls.push({sql,v});if(sql==='BEGIN READ WRITE'){backup={invoice:{...invoice},receipt:{...receipt},paid};return {rows:[]};}if(sql==='ROLLBACK'){Object.assign(invoice,backup.invoice);Object.assign(receipt,backup.receipt);paid=backup.paid;return {rows:[]};}if(sql.startsWith('SELECT role'))return {rows:[{role:denied?'client':'admin',is_active:true}]};if(sql.startsWith('SELECT id,invoice_id'))return {rows:[receipt]};if(sql.startsWith('SELECT * FROM receipts'))return {rows:[{...receipt}]};if(sql.startsWith('SELECT * FROM invoices'))return {rows:[{...invoice}]};if(sql.startsWith('SELECT id FROM invoice_items'))return {rows:[{id:1}]};if(sql.startsWith('SELECT COALESCE'))return {rows:[{paid}]};if(sql.startsWith('UPDATE receipts')){receipt.status='issued';paid+=Number(receipt.amount);}if(sql.startsWith('UPDATE invoices'))invoice.status=v[0];if(sql.startsWith('INSERT INTO ledger_remote_issue_events')&&failAudit)throw Error('Audit failed');return {rows:[]};}};return {invoice,receipt,calls,connect:async()=>db};}
const invoiceInput={kind:'invoice',id:2,number:invoiceBase.invoice_number,shipmentRef:invoiceBase.shipment_ref};const receiptInput={kind:'receipt',id:3,number:receiptBase.receipt_number};
test('issue invoice preserves number, full declaration, creator and UUID; retry is safe',async()=>{const db=fake();const result=await issueDocument(db,invoiceInput,admin,true);assert.equal(result.status,'issued');assert.equal(db.invoice.created_by,9);assert.equal(db.invoice.sync_id,'unchanged');assert.equal(db.invoice.invoice_number,invoiceBase.invoice_number);assert.equal(db.invoice.shipment_ref,invoiceBase.shipment_ref);assert.equal((await issueDocument(db,invoiceInput,admin,true)).replayed,true);assert.equal(db.calls.filter(c=>c.sql.startsWith('INSERT INTO ledger_remote_issue_events')).length,1);});
test('fully advanced invoice becomes paid; zero invoice follows Desktop resolution',()=>{assert.equal(invoiceStatus({...invoiceBase,advance_payment:'100'},0),'paid');assert.equal(invoiceStatus({subtotal:0,total:0},0),'paid');});
test('issued receipt counts and settles invoice, preserves receipt identity and creator',async()=>{const db=fake({invoice:{...invoiceBase,status:'issued'}});await issueDocument(db,receiptInput,admin,true);assert.equal(db.receipt.status,'issued');assert.equal(db.invoice.status,'paid');assert.equal(db.receipt.receipt_number,receiptBase.receipt_number);assert.equal(db.receipt.created_by,9);await issueDocument(db,receiptInput,admin,true);assert.equal(db.calls.filter(c=>c.sql.startsWith('UPDATE receipts')).length,1);});
test('overpayment, draft linked invoice, wrong client and cancelled documents cannot issue',async()=>{for(const changes of [{paid:1},{invoice:{...invoiceBase}},{invoice:{...invoiceBase,status:'issued',client_id:4}},{receipt:{...receiptBase,status:'cancelled'}}]){const db=fake({invoice:{...invoiceBase,status:'issued'},...changes});await assert.rejects(issueDocument(db,receiptInput,admin,true),{status:409});assert.equal(db.receipt.status,changes.receipt?.status||'draft');assert.ok(db.calls.some(c=>c.sql==='ROLLBACK'));}});
test('fresh permission revocation, client accounts and disabled saving deny issue',async()=>{assert.equal(canIssue({role:'client'},'receipt'),false);assert.equal(canIssue({role:'manager',permissions:{canEditReceipts:true}},'receipt'),true);await assert.rejects(issueDocument(null,invoiceInput,admin,false),{status:409});await assert.rejects(issueDocument(null,invoiceInput,{role:'user'},true),{status:403});const db=fake({denied:true});await assert.rejects(issueDocument(db,invoiceInput,admin,true),{status:403});assert.equal(db.invoice.status,'draft');});
test('changed full declaration or number rejected; audit failure rolls issue back',async()=>{for(const input of [{...invoiceInput,shipmentRef:'12345678901234 (2)'},{...invoiceInput,number:'other'}])await assert.rejects(issueDocument(fake(),input,admin,true),{status:409});const db=fake({failAudit:true});await assert.rejects(issueDocument(db,invoiceInput,admin,true),/Audit failed/);assert.equal(db.invoice.status,'draft');});
test('standalone receipt remains valid without invoice; zero amount is rejected',()=>{assert.doesNotThrow(()=>validateReceiptIssue({...receiptBase,invoice_id:null},null,0));assert.throws(()=>validateReceiptIssue({...receiptBase,amount:'0'},null,0),{status:400});});
