import test from 'node:test';import assert from 'node:assert/strict';import {readReceiptEdit,updateReceipt,canEditReceipt} from '../receipt-edit.mjs';
const current={id:3,receipt_number:'REC-W-2026-0001',client_id:1,invoice_id:2,amount:'10.00',payment_method:'cash',status:'issued',notes:'',receipt_date:'2026-10-07'};
const user={id:1,role:'admin'};
function fake(opts={}){const calls=[];return {calls,query:async()=>({rows:[current]}),connect:async()=>({release(){},async query(sql,v){calls.push({sql,v});if(sql.startsWith('SELECT role'))return {rows:[{role:'admin',is_active:true}]};if(sql.startsWith('SELECT created_by'))return {rows:[]};if(sql.startsWith('SELECT id,created_by,receipt_number'))return {rows:[opts.stale?{...current,notes:'another edit'}:current]};if(sql.startsWith('SELECT id FROM clients'))return {rows:[{id:1}]};if(sql.startsWith('SELECT id,client_id'))return {rows:[{id:2,client_id:1,status:'issued',subtotal:'100',tax_amount:'0',advance_payment:'0'}]};if(sql.startsWith('SELECT COALESCE'))return {rows:[{paid:'80'}]};return {rows:[]};}})};}
async function input(db){const d=await readReceiptEdit(db,3,user);return {id:3,version:d.version,syncId:'a4483e87-3982-4e11-9cb6-7eeae233243e',clientId:1,invoiceId:2,date:'2026-10-07',amount:'15',paymentMethod:'cash',notes:'new'};}
test('receipt update keeps identity and status, recomputes invoice payment state',async()=>{const db=fake();await updateReceipt(db,await input(db),user,true);const q=db.calls.find(x=>x.sql.startsWith('UPDATE receipts'));assert.equal(q.sql.includes('receipt_number='),false);assert.equal(q.sql.includes('status=$8'),true);assert.equal(q.v[6],3);assert.equal(q.v[7],'issued');assert.ok(db.calls.some(x=>x.sql.startsWith('UPDATE invoices')));assert.ok(db.calls.some(x=>x.sql==='COMMIT'));});
test('overpayment and stale edits roll back',async()=>{for(const stale of [false,true]){const db=fake({stale});const data=await input(db);if(!stale)data.amount='30';await assert.rejects(updateReceipt(db,data,user,true),{status:409});assert.ok(db.calls.some(x=>x.sql==='ROLLBACK'));assert.equal(db.calls.some(x=>x.sql.startsWith('UPDATE receipts')),false);}});
test('client user and disabled writes denied',async()=>{assert.equal(canEditReceipt({role:'client'}),false);await assert.rejects(updateReceipt(null,{},user,false),{status:409});await assert.rejects(readReceiptEdit(null,3,{role:'client'}),{status:403});});

test('receipt status changes update original ID and recompute collections; invalid status denied',async()=>{for(const status of ['draft','issued','cancelled']){const db=fake();await updateReceipt(db,{...await input(db),status},user,true);const q=db.calls.find(x=>x.sql.startsWith('UPDATE receipts'));assert.equal(q.v[6],3);assert.equal(q.v[7],status);assert.ok(db.calls.some(x=>x.sql.startsWith('UPDATE invoices')));}const db=fake();await assert.rejects(updateReceipt(db,{...await input(db),status:'paid'},user,true),{status:400});});
