import test from 'node:test';import assert from 'node:assert/strict';import {changeTrash} from '../trash-actions.mjs';
const admin={id:1,role:'admin'},number='INV-W-2026-0001';
function fake({kind='invoice',linked=false,parentDeleted=false,failAudit=false,deleted=true}={}){
 let state={row:{id:2,invoice_number:number,receipt_number:'REC-W-2026-0001',invoice_id:kind==='receipt'?3:null,status:'cancelled',deleted_at:deleted?'2026-10-08':null,sync_id:'uuid',client_id:1,amount:10},archive:false,marker:null,items:true,draft:true},backup;const calls=[];
 const db={release(){},async query(sql,v=[]){calls.push({sql,v});const rows=x=>({rows:x});if(sql==='BEGIN READ WRITE'){backup=structuredClone(state);return rows([]);}if(sql==='ROLLBACK'){state=backup;return rows([]);}if(sql==='COMMIT'||/^(CREATE|DROP)/.test(sql))return rows([]);if(sql.startsWith('SELECT role'))return rows([{role:'admin',is_active:true}]);if(sql.startsWith('SELECT id,invoice_id'))return rows(state.row?[{id:2,invoice_id:3}]:[]);if(sql.startsWith('SELECT id,invoice_number'))return rows([{id:3,invoice_number:'PARENT',status:'draft',deleted_at:parentDeleted?'2026-10-08':null}]);if(sql.startsWith('SELECT * FROM'))return rows(state.row?[{...state.row}]:[]);if(sql.startsWith('SELECT id FROM receipts'))return rows(linked?[{id:10}]:[]);if(sql.startsWith('SELECT to_regclass'))return rows([{drafts:true}]);if(sql.startsWith('SELECT number FROM ledger_remote_permanent'))return rows(state.archive?[{number:kind==='invoice'?number:'REC-W-2026-0001'}]:[]);if(sql.startsWith('UPDATE')){state.row.deleted_at=null;state.row.status='draft';return rows([]);}if(sql.startsWith('INSERT INTO ledger_remote_permanent')){state.archive=true;return rows([]);}if(sql.startsWith('DELETE FROM ledger_remote')){state.draft=false;return rows([]);}if(sql.startsWith('DELETE FROM invoice_items')){state.items=false;return rows([]);}if(sql.startsWith('DELETE FROM invoices')||sql.startsWith('DELETE FROM receipts')){state.row=null;return rows([]);}if(sql.startsWith('INSERT INTO ledger_document_sync_changes')){state.marker=v[2];return rows([]);}if(sql.startsWith('INSERT INTO ledger_remote_trash_events')){if(failAudit)throw Error('Audit failed');return rows([]);}throw Error(sql);}};
 return {connect:async()=>db,calls,get state(){return state;}};
}
const input={kind:'invoice',id:2,number,action:'restore'};
test('invoice restore returns draft, preserves identity and never restores linked receipts',async()=>{const db=fake({linked:true});await changeTrash(db,input,admin,true);assert.equal(db.state.row.status,'draft');assert.equal(db.state.row.deleted_at,null);assert.equal(db.state.row.invoice_number,number);assert.equal(db.state.marker,'restore');assert.equal(db.calls.some(c=>c.sql.startsWith('UPDATE receipts')),false);});
test('receipt restore requires active parent and restores as draft without counting payment',async()=>{for(const parentDeleted of [false,true]){const db=fake({kind:'receipt',parentDeleted});const request={...input,kind:'receipt',number:'REC-W-2026-0001'};if(parentDeleted){await assert.rejects(changeTrash(db,request,admin,true),{status:409});assert.equal(db.state.row.status,'cancelled');}else{await changeTrash(db,request,admin,true);assert.equal(db.state.row.status,'draft');assert.equal(db.state.marker,'restore');}}});
test('permanent invoice deletion retains recreation guard, removes source draft/items and safely replays',async()=>{const db=fake();const request={...input,action:'purge'};await changeTrash(db,request,admin,true);assert.equal(db.state.row,null);assert.equal(db.state.items,false);assert.equal(db.state.draft,false);assert.equal(db.state.archive,true);assert.equal(db.state.marker,'delete');assert.ok(db.calls.some(c=>c.sql.includes('PERMANENTLY_DELETED_INVOICE')));assert.ok(db.calls.some(c=>c.sql.includes('BEFORE INSERT OR UPDATE')));assert.equal((await changeTrash(db,request,admin,true)).replayed,true);});
test('invoice purge requires linked receipts removed first; active records cannot be purged',async()=>{for(const opts of [{linked:true},{deleted:false}]){const db=fake(opts);await assert.rejects(changeTrash(db,{...input,action:'purge'},admin,true),{status:409});assert.ok(db.state.row);assert.equal(db.state.archive,false);}});
test('audit failure rolls back restore and permanent purge including archive/drafts/items',async()=>{for(const action of ['restore','purge']){const db=fake({failAudit:true});await assert.rejects(changeTrash(db,{...input,action},admin,true),/Audit failed/);assert.equal(db.state.row.status,'cancelled');assert.ok(db.state.row.deleted_at);assert.equal(db.state.archive,false);assert.equal(db.state.items,true);assert.equal(db.state.draft,true);assert.equal(db.state.marker,null);}});
test('trash actions deny clients, disabled writes, malformed identities and changed number',async()=>{await assert.rejects(changeTrash(null,input,{role:'client'},true),{status:403});await assert.rejects(changeTrash(null,input,admin,false),{status:409});await assert.rejects(changeTrash(null,{...input,action:'sql'},admin,true),{status:400});await assert.rejects(changeTrash(fake(),{...input,number:'other'},admin,true),{status:409});});
