import { pgTable, serial, text, boolean, timestamp, integer } from "drizzle-orm/pg-core";

export const companySettingsTable = pgTable("company_settings", {
  id: serial("id").primaryKey(),
  nameAr: text("name_ar").notNull().default("اسم الشركة للتخليص الجمركي"),
  nameEn: text("name_en").notNull().default("Company Name Customs Clearance"),
  subtitleAr: text("subtitle_ar").default("للتخليص الجمركي"),
  subtitleEn: text("subtitle_en").default("Customs Clearance"),
  taglineAr: text("tagline_ar").default("خدمات التخليص الجمركي والشحن"),
  taglineEn: text("tagline_en").default("Customs Clearance & Shipping Services"),
  email: text("email").default("atwcc1246@gmail.com"),
  phone: text("phone").default("55251595"),
  address: text("address").default("Doha, Qatar"),
  poBox: text("po_box").default("P.O BOX 8180"),
  website: text("website"),
  crNumber: text("cr_number"),
  taxNumber: text("tax_number"),
  logoBase64: text("logo_base64"),
  stampBase64: text("stamp_base64"),
  watermarkBase64: text("watermark_base64"),
  showWatermark: boolean("show_watermark").notNull().default(true),
  showStampOnInvoices: boolean("show_stamp_on_invoices").notNull().default(true),
  showStampOnReceipts: boolean("show_stamp_on_receipts").notNull().default(true),
  showStampOnStatements: boolean("show_stamp_on_statements").notNull().default(true),
  footerText: text("footer_text"),

  invoiceCashTitleAr: text("invoice_cash_title_ar"),
  invoiceCashTitleEn: text("invoice_cash_title_en"),
  invoiceCreditTitleAr: text("invoice_credit_title_ar"),
  invoiceCreditTitleEn: text("invoice_credit_title_en"),
  invoiceTitleFontSize: integer("invoice_title_font_size").default(25),
  invoiceTitleVisible: boolean("invoice_title_visible").notNull().default(true),
  invoiceTitleAlign: text("invoice_title_align").default("center"),
  invoiceTitleBold: boolean("invoice_title_bold").notNull().default(true),
  invoiceSubtitleAr: text("invoice_subtitle_ar").default(""),
  invoiceSubtitleEn: text("invoice_subtitle_en").default(""),
  invoiceSubtitleFontSize: integer("invoice_subtitle_font_size").default(12),
  statementTitleAr: text("statement_title_ar").default("كشف حساب"),
  statementTitleEn: text("statement_title_en").default("Statement"),
  statementTitleFontSize: integer("statement_title_font_size").default(18),
  statementTitleVisible: boolean("statement_title_visible").notNull().default(true),
  statementTitleAlign: text("statement_title_align").default("center"),
  statementTitleBold: boolean("statement_title_bold").notNull().default(true),
  statementSubtitleAr: text("statement_subtitle_ar").default(""),
  statementSubtitleEn: text("statement_subtitle_en").default(""),
  statementSubtitleFontSize: integer("statement_subtitle_font_size").default(12),
  customerLedgerTitleAr: text("customer_ledger_title_ar").default("ملخص العميل المالي"),
  customerLedgerTitleEn: text("customer_ledger_title_en").default("Customer Financial Summary"),
  customerLedgerTitleFontSize: integer("customer_ledger_title_font_size").default(18),
  customerLedgerTitleVisible: boolean("customer_ledger_title_visible").notNull().default(true),
  customerLedgerTitleAlign: text("customer_ledger_title_align").default("center"),
  customerLedgerTitleBold: boolean("customer_ledger_title_bold").notNull().default(true),
  customerLedgerSubtitleAr: text("customer_ledger_subtitle_ar").default(""),
  customerLedgerSubtitleEn: text("customer_ledger_subtitle_en").default(""),
  customerLedgerSubtitleFontSize: integer("customer_ledger_subtitle_font_size").default(12),
  
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export type CompanySettings = typeof companySettingsTable.$inferSelect;
export type InsertCompanySettings = typeof companySettingsTable.$inferInsert;
[]
