import { sqliteTable, integer, text } from "drizzle-orm/sqlite-core";

export const companySettingsTableSqlite = sqliteTable("company_settings", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  nameAr: text("name_ar").notNull().default("اسم الشركة للتخليص الجمركي"),
  nameEn: text("name_en").notNull().default("Company Name Customs Clearance"),
  subtitleAr: text("subtitle_ar").default("للتخليص الجمركي"),
  subtitleEn: text("subtitle_en").default("Customs Clearance"),
  taglineAr: text("tagline_ar").default("خدمات التخليص الجمركي والشحن"),
  taglineEn: text("tagline_en").default("Customs Clearance & Shipping Services"),
  email: text("email").default("atwcc1246@gmail.com"),
  phone: text("phone").default("55251595"),
  address: text("address").default("Doha, Qatar"),
  poBox: text("po_box").default("P.O BOX 8180"),
  website: text("website"),
  crNumber: text("cr_number"),
  taxNumber: text("tax_number"),
  logoBase64: text("logo_base64"),
  logoSize: integer("logo_size").default(80),
  stampBase64: text("stamp_base64"),
  watermarkBase64: text("watermark_base64"),
  showWatermark: integer("show_watermark", { mode: "boolean" }).default(true),
  showStampOnInvoices: integer("show_stamp_on_invoices", { mode: "boolean" }).default(true),
  showStampOnReceipts: integer("show_stamp_on_receipts", { mode: "boolean" }).default(true),
  showStampOnStatements: integer("show_stamp_on_statements", { mode: "boolean" }).default(true),
  footerText: text("footer_text"),
  invoiceCashTitleAr: text("invoice_cash_title_ar"),
  invoiceCashTitleEn: text("invoice_cash_title_en"),
  invoiceCreditTitleAr: text("invoice_credit_title_ar"),
  invoiceCreditTitleEn: text("invoice_credit_title_en"),
  invoiceTitleFontSize: integer("invoice_title_font_size").default(25),
  invoiceTitleVisible: integer("invoice_title_visible", { mode: "boolean" }).default(true),
  invoiceTitleAlign: text("invoice_title_align").default("center"),
  invoiceTitleBold: integer("invoice_title_bold", { mode: "boolean" }).default(true),
  invoiceSubtitleAr: text("invoice_subtitle_ar").default(""),
  invoiceSubtitleEn: text("invoice_subtitle_en").default(""),
  invoiceSubtitleFontSize: integer("invoice_subtitle_font_size").default(12),
  statementTitleAr: text("statement_title_ar").default("كشف حساب"),
  statementTitleEn: text("statement_title_en").default("Statement"),
  statementTitleFontSize: integer("statement_title_font_size").default(18),
  statementTitleVisible: integer("statement_title_visible", { mode: "boolean" }).default(true),
  statementTitleAlign: text("statement_title_align").default("center"),
  statementTitleBold: integer("statement_title_bold", { mode: "boolean" }).default(true),
  statementSubtitleAr: text("statement_subtitle_ar").default(""),
  statementSubtitleEn: text("statement_subtitle_en").default(""),
  statementSubtitleFontSize: integer("statement_subtitle_font_size").default(12),
  customerLedgerTitleAr: text("customer_ledger_title_ar").default("ملخص العميل المالي"),
  customerLedgerTitleEn: text("customer_ledger_title_en").default("Customer Financial Summary"),
  customerLedgerTitleFontSize: integer("customer_ledger_title_font_size").default(18),
  customerLedgerTitleVisible: integer("customer_ledger_title_visible", { mode: "boolean" }).default(true),
  customerLedgerTitleAlign: text("customer_ledger_title_align").default("center"),
  customerLedgerTitleBold: integer("customer_ledger_title_bold", { mode: "boolean" }).default(true),
  customerLedgerSubtitleAr: text("customer_ledger_subtitle_ar").default(""),
  customerLedgerSubtitleEn: text("customer_ledger_subtitle_en").default(""),
  customerLedgerSubtitleFontSize: integer("customer_ledger_subtitle_font_size").default(12),
  accountantSignatureBase64: text("accountant_signature_base64"),
  receiverSignatureBase64: text("receiver_signature_base64"),
  showAccountantSignature: integer("show_accountant_signature", { mode: "boolean" }).default(true),
  showReceiverSignature: integer("show_receiver_signature", { mode: "boolean" }).default(true),
  allowManagerEditAccountantSignature: integer("allow_manager_edit_accountant_signature", { mode: "boolean" }).default(false),
  allowManagerEditLegalInfo: integer("allow_manager_edit_legal_info", { mode: "boolean" }).default(false),
  allowManagerEditInvoicesBackupImport: integer("allow_manager_edit_invoices_backup_import", { mode: "boolean" }).default(false),
  allowManagerEditAppearance: integer("allow_manager_edit_appearance", { mode: "boolean" }).default(false),
  allowManagerEditPrintSettings: integer("allow_manager_edit_print_settings", { mode: "boolean" }).default(false),
  allowManagerEditBranding: integer("allow_manager_edit_branding", { mode: "boolean" }).default(false),
  allowManagerEditRegistrationSettings: integer("allow_manager_edit_registration_settings", { mode: "boolean" }).default(false),
  allowManagerEditSensitiveUsers: integer("allow_manager_edit_sensitive_users", { mode: "boolean" }).default(false),
  lockCompanyIdentity: integer("lock_company_identity", { mode: "boolean" }).default(false),
  lockCompanyName: integer("lock_company_name", { mode: "boolean" }).default(false),
  lockLogo: integer("lock_logo", { mode: "boolean" }).default(false),
  lockStamp: integer("lock_stamp", { mode: "boolean" }).default(false),
  lockLegalInfo: integer("lock_legal_info", { mode: "boolean" }).default(false),
  lockFooterBranding: integer("lock_footer_branding", { mode: "boolean" }).default(false),
  preventRebrandToAnotherCompany: integer("prevent_rebrand_to_another_company", { mode: "boolean" }).default(false),
  licenseStatus: text("license_status").default("not_configured"),
  licensedCompanyName: text("licensed_company_name").default(""),
  licenseId: text("license_id").default(""),
  hardwareId: text("hardware_id").default(""),
  issuedAt: text("issued_at").default(""),
  expiresAt: text("expires_at").default(""),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }),
  masterPasswordHash: text("master_password_hash"),
});

export type CompanySettingsSqlite = typeof companySettingsTableSqlite.$inferSelect;
export type InsertCompanySettingsSqlite = typeof companySettingsTableSqlite.$inferInsert;
