import { sqliteTable, integer, text } from "drizzle-orm/sqlite-core";

export const companySettingsTableSqlite = sqliteTable("company_settings", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  nameAr: text("name_ar").notNull().default("اسم الشركة للتخليص الجمركي"),
  nameEn: text("name_en").notNull().default("Company Name Customs Clearance"),
  subtitleAr: text("subtitle_ar").default("للتخليص الجمركي"),
  subtitleEn: text("subtitle_en").default("Customs Clearance"),
  taglineAr: text("tagline_ar").default("خدمات التخليص الجمركي والشحن"),
  taglineEn: text("tagline_en").default("Customs Clearance & Shipping Services"),
  email: text("email").default("atwcc1246@gmail.com"),
  phone: text("phone").default("55251595"),
  address: text("address").default("Doha, Qatar"),
  poBox: text("po_box").default("P.O BOX 8180"),
  website: text("website"),
  crNumber: text("cr_number"),
  taxNumber: text("tax_number"),
  logoBase64: text("logo_base64"),
  logoSize: integer("logo_size").default(80),
  stampBase64: text("stamp_base64"),
  watermarkBase64: text("watermark_base64"),
  showWatermark: integer("show_watermark", { mode: "boolean" }).default(true),
  showStampOnInvoices: integer("show_stamp_on_invoices", { mode: "boolean" }).default(true),
  showStampOnReceipts: integer("show_stamp_on_receipts", { mode: "boolean" }).default(true),
  showStampOnStatements: integer("show_stamp_on_statements", { mode: "boolean" }).default(true),
  footerText: text("footer_text"),
  invoiceCashTitleAr: text("invoice_cash_title_ar"),
  invoiceCashTitleEn: text("invoice_cash_title_en"),
  invoiceCreditTitleAr: text("invoice_credit_title_ar"),
  invoiceCreditTitleEn: text("invoice_credit_title_en"),
  invoiceTitleFontSize: integer("invoice_title_font_size").default(25),
  accountantSignatureBase64: text("accountant_signature_base64"),
  receiverSignatureBase64: text("receiver_signature_base64"),
  showAccountantSignature: integer("show_accountant_signature", { mode: "boolean" }).default(true),
  showReceiverSignature: integer("show_receiver_signature", { mode: "boolean" }).default(true),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }),
});

export type CompanySettingsSqlite = typeof companySettingsTableSqlite.$inferSelect;
export type InsertCompanySettingsSqlite = typeof companySettingsTableSqlite.$inferInsert;